name: "3 - [HOM] Promote & Deploy"

on:
  pull_request:
    types: closed
    branches: 'release/**'

jobs:
  infra:
    uses: fleetfy/fleetfy-reusable-commons-infra-workflows/.github/workflows/homolog.yml@v1
    secrets: inherit